In [ ]:
Why NumPy Arrays?
NumPy arrays are the core of numerical computing in Python. They are:

Faster than Python lists (C-optimized)
Memory-efficient (store data in a contiguous block)
Support vectorized operations that support SIMD (no slow Python loops)
Used in ML, Data Science, and AI

1. Creating NumPy Arrays

In [2]:
import numpy as np

In [3]:
!pip install numpy

 Unlike lists, all elements must have the same data type.

In [4]:
arr  = np.array([1,2,3]) #1D array

In [43]:
np.zeros((3,3)) # 3x3 array of zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((3,5)) # 3x5 array of ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.full((4,6) ,8) # 4x6 array filled with 8

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [8]:
np.eye(3) # 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
np.arange(1,100,2) # [1, 3, 5, 7, 9....] (like range)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [47]:
np.linspace(1,100,5) # [0. 0.25 0.5 0.75 1.] (evenly spaced)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

2. Checking Array Properties

In [48]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [21]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [22]:
myarr.shape

(4, 3)

In [23]:
myarr.size

12

In [24]:
myarr.ndim

2

3. Changing Data Types

In [25]:
myarr.dtype

dtype('int64')

In [26]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]] , dtype = 'float32')

In [27]:
myarr.dtype

dtype('float32')

In [30]:
n = myarr.astype('int32')

In [32]:
n.dtype

dtype('int32')

4. Reshaping and Flattening Arrays

In [33]:
n.shape

(4, 3)

In [38]:
reshaped = n.reshape(6,2) # Change shape

In [39]:
print(reshaped)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 11],
       [12, 13]], dtype=int32)

In [50]:
flattened = myarr.flatten() # Convert 2D → 1D
print(flattened)

[ 1  2  3  4  5  6  7  8  9 11 12 13]
