NumPy arrays are homogeneous, meaning that they can only store elements of the same type. This is different from Python lists, which can hold mixed data types. NumPy supports various data types (also called dtypes), and understanding them is crucial for optimizing memory usage and performance.


Common Data Types in NumPy:
int32, int64: Integer types with different bit sizes.
float32, float64: Floating-point types with different precision.
bool: Boolean data type.
complex64, complex128: Complex number types.
object: For storing objects (e.g., Python objects, strings).

In [2]:
import numpy as np
arr = np.array([1,2,3,45,5])
print(arr.dtype)

int64


 Changing Data Types:

In [3]:
arr.astype("float32")

array([ 1.,  2.,  3., 45.,  5.], dtype=float32)

Downcasting to Save Memory

In [12]:
arr_large = np.array([1000000, 2000000, 3000000], dtype=np.int64)
arr_small = arr_large.astype(np.int32)  # Downcasting to a smaller dtype
print(arr_small)  # Output: [1000000 2000000 3000000]
print(arr_small.dtype)  # Output: int32

[1000000 2000000 3000000]
int32


Why Data Types Matter in NumPy
The choice of data type affects:

Memory Usage: Smaller data types use less memory.
Performance: Operations on smaller data types are faster due to less data being processed.
Precision: Choosing the appropriate data type ensures that you don't lose precision (e.g., using float32 instead of float64 if you don't need that extra precision).

Memory Usage:

In [9]:
arr2 = np.array([1,2,3,45,5] , dtype="float32")


In [10]:
arr2

array([ 1.,  2.,  3., 45.,  5.], dtype=float32)

In [11]:
arr2.nbytes

20

String Data Type in NumPy
Although NumPy arrays typically store numerical data, you can also store strings by using the dtype='str' or dtype='U' (Unicode string) format. However, working with strings in NumPy is less efficient than using lists or Python's built-in string types.

In [13]:
arr = np.array(['apple', 'banana', 'cherry'], dtype='U10')  # Unicode string array
print(arr)

['apple' 'banana' 'cherry']


5. Complex Numbers
NumPy also supports complex numbers, which consist of a real and imaginary part. You can store complex numbers using complex64 or complex128 data types.

In [14]:
arr = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype='complex128')
print(arr)

[1.+2.j 3.+4.j 5.+6.j]


Object Data Type:
If you need to store mixed or complex data types (e.g., Python objects), you can use dtype='object'. However, this type sacrifices performance, so it should only be used when absolutely necessary.

In [15]:
arr = np.array([{'a': 1}, [1, 2, 3], 'hello'], dtype=object)
print(arr)

[{'a': 1} list([1, 2, 3]) 'hello']


Choosing the Right Data Type
Choosing the correct data type is essential for:

Optimizing memory: Using the smallest data type that fits your data.
Improving performance: Smaller types generally lead to faster operations.
Ensuring precision: Avoid truncating or losing important decimal places or values.
