In [2]:
import numpy as np
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [3]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [6]:
flat = myarr.flatten()

In [7]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [ ]:
Indexing (Same as Python Lists)

In [8]:
flat[0]

1

In [ ]:
Slicing (Extracting Parts of an Array)

In [9]:
flat[:5] # same as flat[0:5]

array([1, 2, 3, 4, 5])

In [10]:
flat[3:] # same as flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

Slicing returns a view, not a copy! Changes affect the original array.**
This might seem counterintuitive since Python lists create copies when sliced. But in NumPy, slicing returns a view of the original array. Both the sliced array and the original array share the same data in memory, so changes in the slice affect the original array. with copy() to make copy of existing array

In [18]:
flat
b = flat[3:6] #b = flat[3:6].copy()

b[0] = 44444

In [19]:
b

array([44444,     5,     6])

In [20]:
flat

array([    1,     2,     3, 44444,     5,     6,     7,     8,     9,
          11,    12,    13])

In [23]:
# Fancy Indexing (Select Multiple Elements)
arr = np.array([10,20,30,40])
ind = [0,1,2]
print(arr[ind])

[10 20 30]


Boolean Masking (Filter Data)

In [26]:
arr2 = np.array([10, 20, 30, 40, 50])
mask = arr2 > 25  # Condition: values greater than 25
print(arr2[mask])  # [30 40 50]

[30 40 50]


exercise questions:
Create a 3×3 array filled with random numbers and print its shape.
Convert an array of floats [1.1, 2.2, 3.3] into integers.
Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
Reshape a 1D array of size 9 into a 3×3 matrix.
Use boolean masking to filter numbers greater than 50 in an array.

In [27]:
import numpy as np

# 1. Create a 3×3 array filled with random numbers and print its shape
arr_random = np.random.rand(3, 3)
print("Random Array:\n", arr_random)
print("Shape:", arr_random.shape)

# 2. Convert an array of floats [1.1, 2.2, 3.3] into integers
float_arr = np.array([1.1, 2.2, 3.3])
int_arr = float_arr.astype(int)
print("\nInteger Array:", int_arr)

# 3. Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6]
arr = np.array([1, 2, 3, 4, 5, 6])
even_numbers = arr[[1, 3, 5]]  # indices of even values
print("\nEven Numbers (Fancy Indexing):", even_numbers)

# 4. Reshape a 1D array of size 9 into a 3×3 matrix
one_d = np.arange(1, 10)
matrix = one_d.reshape(3, 3)
print("\n3x3 Matrix:\n", matrix)

# 5. Use boolean masking to filter numbers greater than 50 in an array
numbers = np.array([10, 55, 23, 78, 49, 90, 12])
filtered = numbers[numbers > 50]
print("\nNumbers > 50:", filtered)

Random Array:
 [[0.12882509 0.73788978 0.92747819]
 [0.07794833 0.59860796 0.97469653]
 [0.34204232 0.12873341 0.11950306]]
Shape: (3, 3)

Integer Array: [1 2 3]

Even Numbers (Fancy Indexing): [2 4 6]

3x3 Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Numbers > 50: [55 78 90]
