In [1]:
import numpy as np

In [22]:
arr = np.array([1,2,3,4,5,6])
arr1 = np.array([1,2,3,4,5,6])

In [5]:
np.mean(arr) #Compute the mean (average) of an array.

3.5

In [8]:
np.min(arr) #Compute the minimum value of an array.

1

In [9]:
np.max(arr) #Compute the maximum value of an array.

6

In [10]:
np.sum(arr) #Compute the sum of all elements in an array.

21

In [11]:
np.std(arr) #Compute the standard deviation of an array.

1.707825127659933

In [12]:
np.var(arr) #Compute the variance of an array.

2.9166666666666665

In [14]:
np.median(arr) #Compute the median of an array.

3.5

In [13]:
np.prod(arr) #Compute the product of all elements in an array.

720

In [17]:
np.percentile(arr,50) # For the 50th percentile (median)


3.5

In [18]:
np.argmin(arr) #Return the index of the minimum value in an array.

0

In [19]:
np.argmax(arr) #  Return the index of the maximum value in an array.

5

In [23]:
np.corrcoef(arr,arr1) #Compute the correlation coefficient matrix of two arrays.

array([[1., 1.],
       [1., 1.]])

In [24]:
np.unique(arr) # Find the unique elements of an array.

array([1, 2, 3, 4, 5, 6])

In [25]:
np.diff(arr) #Compute the n-th differences of an array.

array([1, 1, 1, 1, 1])

In [26]:
np.cumsum(arr) #Compute the cumulative sum of an array.

array([ 1,  3,  6, 10, 15, 21])

In [27]:
np.linspace(0, 10, 5)  # 5 numbers from 0 to 10 #Create an array with evenly spaced numbers over a specified interval.

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [28]:
np.log(arr) #Compute the natural logarithm of an array.

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947])

In [29]:
np.exp(arr) # Compute the exponential of an array.

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 , 403.42879349])