1. Understanding Axes in NumPy
Each dimension in a NumPy array is called an axis. Axes are numbered starting from 0.

For example:

1D array → 1 axis (axis 0)
2D array → 2 axes (axis 0 = rows, axis 1 = columns)
3D array → 3 axes (axis 0 = depth, axis 1 = rows, axis 2 = columns)

In [ ]:
Example: Axes in a 2D Array

In [1]:
import numpy as np
arr = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [2]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr[0]
np.sum(arr, axis=0) # Sum along rows (down each column)

array([12, 15, 18])

In [9]:
np.sum(arr, axis=1) # Sum along columns (across each row)

array([ 6, 15, 24])

2. Indexing in Multidimensional Arrays

In [12]:
arr[1][0] 

4

You can also use slicing to extract parts of an array:

In [13]:
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

3. Indexing in 3D Arrays

In [14]:
arr3d = np.array([
                  [[1,2,3],
                  [4,5,6]],
                 
                [[7,8,9],
                 [10,11,12]]
])


In [15]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [18]:
print(arr3d[1,1,1]) #3D array → 3 axes (axis 0 = depth, axis 1 = rows, axis 2 = columns)

11


In [20]:
print(arr3d[:, 0, :])   # Get the first row from both sheets

[[1 2 3]
 [7 8 9]]


In [21]:
print(arr3d[0, 0, 0]) 

1


In [22]:
print(arr3d[:, 0, 0]) 

[1 7]


4. Practical Example: Selecting Data Along Axes

In [23]:
# Get all rows of the first column
first_col = arr[:,1]
print(first_col)

[2 5 8]


In [25]:
# Get the first row from each "sheet" in a 3D array
first_rows = arr3d[:, 0, :]
print(first_rows)

[[1 2 3]
 [7 8 9]]


5. Changing Data Along an Axis

In [ ]:
arr[:,1] = 